dataset:
  oad_from_disk: False
  dataset_path: "solarcube_image_"
  dataset_source: "solarcube"
  time_res: "15min"
  img_height: 120
  img_width: 120
  train_tile_list: [1, 2, 3, 4, 6, 8, 10, 12, 13, 14, 15, 16, 17, 19]
  test_tile_list: [5, 7, 9, 11, 18]
  train_year_list: ['2018']
  test_year_list: ['2018']
  x_img_types: ['ssr']
  y_img_types: ['ssr']
  input_len: 12
  output_len: 12
  sample_interval: 8
  downscale_s: False
  downscale_t: False
  seq_len: None
  plot_stride: 2
  interval_real_time: 15
  stride: 12
  layout: "THWC"
  start_date: None
  end_date: None
  datetime_filter: None
  catalog_filter: None
  unwrap_time: False
  shuffle: False
  pin_memory: True
  output_type: np.float32
  normalize_x: False
  normalize_y: False
  normalize_max: True
  point_based: False
  batch_size: 1
  ignorenan: False
layout:
  in_len: 12
  out_len: 12
  layout: "NTHWC"
optim:
  total_batch_size: 1
  micro_batch_size: 1
  seed: 0
  method: "adamw"
  lr: 0.001
  wd: 0.0
  gradient_clip_val: 1.0
  max_epochs: 100
  # scheduler
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 1.0e-3
  warmup_min_lr_ratio: 0.0
  warmup_percentage: 0.2
  # early stopping
  early_stop: true
  early_stop_mode: "min"
  early_stop_patience: 10
  save_top_k: 1
logging:
  version: "axial"
  logging_prefix: "SolarCube"
  monitor_lr: true
  monitor_device: false
  track_grad_norm: -1
  use_wandb: false
trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001
  precision: 32
vis:
  train_example_data_idx_list: [0, ]
  val_example_data_idx_list: [80, ]
  test_example_data_idx_list: [0, 80, 160, 240, 320, 400]
  eval_example_only: false
  plot_stride: 2
model:
  input_shape: [12, 120, 120, 1]
  target_shape: [12, 120, 120, 1]
  base_units: 64
  block_units: null
  scale_alpha: 1.0

  enc_depth: [4, 4]
  dec_depth: [4, 4]
  enc_use_inter_ffn: true
  dec_use_inter_ffn: true
  dec_hierarchical_pos_embed: false

  downsample: 2
  downsample_type: "patch_merge"
  upsample_type: "upsample"

  num_global_vectors: 0
  use_dec_self_global: false
  dec_self_update_global: true
  use_dec_cross_global: false
  use_global_vector_ffn: false
  use_global_self_attn: false
  separate_global_qkv: false
  global_dim_ratio: 1

  self_pattern: "axial"
  cross_self_pattern: "axial"
  cross_pattern: "cross_1x1"
  dec_cross_last_n_frames: null

  attn_drop: 0.1
  proj_drop: 0.1
  ffn_drop: 0.1
  num_heads: 4

  ffn_activation: "gelu"
  gated_ffn: false
  norm_layer: "layer_norm"
  padding_type: "zeros"
  pos_embed_type: "t+hw"
  use_relative_pos: true
  self_attn_use_final_proj: true
  dec_use_first_self_attn: false

  z_init_method: "zeros"
  initial_downsample_type: "conv"
  initial_downsample_activation: "leaky"
  initial_downsample_scale: 2
  initial_downsample_conv_layers: 2
  final_upsample_conv_layers: 1
  checkpoint_level: 0

  attn_linear_init_mode: "0"
  ffn_linear_init_mode: "0"
  conv_init_mode: "0"
  down_up_linear_init_mode: "0"
  norm_init_mode: "0"